# Database credentials
readerDatabase:
  user: "posteth"
  name: "db"
  host: "localhost"
  port: "5432"
  password: "pass"
  maxOpenConns: 50
  maxIdleConns: 10
  ssl: false
writerDatabase:
  user: "posteth"
  name: "db"
  host: "localhost"
  port: "5432"
  password: "pass"
  maxOpenConns: 50
  maxIdleConns: 10
  ssl: false
# Chain network configuration
chain:
  name: "sepolia"
  configPath: ./config/sepolia.chain.yml
  genesisTimestamp: 1655733600
# Note: It is possible to run either the frontend or the indexer or both at the same time
# Frontend config
frontend:
  enabled: true # Enable or disable to web frontend
  imprint: "./imprint.html"  # Path to the imprint page content
  siteName: "Kintsugi Explorer" # Name of the site, displayed in the title tag
  siteSubtitle: "Kintsugi explorer" # Subtitle shown on the main page
  csrfAuthKey: '0123456789abcdef000000000000000000000000000000000000000000000000'
  jwtSigningSecret: "0123456789abcdef000000000000000000000000000000000000000000000000"
  jwtIssuer: "localblockexplorer"
  jwtValidityInMinutes: 30
  server:
    host: "0.0.0.0" # Address to listen on
    port: "3333" # Port to listen on
  readerDatabase:
    user: "posteth"
    name: "db"
    host: "localhost"
    port: "5432"
    password: "pass"
    maxOpenConns: 50
    maxIdleConns: 10
    ssl: false
  writerDatabase:
    user: "posteth"
    name: "db"
    host: "localhost"
    port: "5432"
    password: "pass"
    maxOpenConns: 50
    maxIdleConns: 10
    ssl: false
  # sessionSecret: "<sessionSecret>"
  # flashSecret: "" # Encryption secret for flash cookies
# Indexer config
indexer:
  enabled: true # Enable or disable the indexing service
  fullIndexOnStartup: true # Perform a one time full db index on startup
  indexMissingEpochsOnStartup: true # Check for missing epochs and export them after startup
  node:
    host: "localhost" # Address of the backend node
    port: "4000" # GRPC port of the Prysm node
    type: "lighthouse" # can be either prysm or lighthouse
    pageSize: 100 # the amount of entries to fetch per paged rpc call, TODO set to 500
  eth1Endpoint: 'http://localhost:8545'
  # Note: 0 is correct, but due to an underflow bug (being fixed), doesn't work.
  eth1DepositContractFirstBlock: 1
  
eth1ErigonEndpoint: 'http://localhost:8545'
eth1GethEndpoint: 'http://localhost:8545'

  # Bigtable configuration (using local emulator for development)
bigtable:
  project: "explorer"
  instance: "explorer"
  emulator: true
  emulatorPort: 9000

# Redis cache endpoint
redisCacheEndpoint: "localhost:6379"

# Session store endpoint  
redisSessionStoreEndpoint: "localhost:6379"

# Tiered cache provider
tieredCacheProvider: "redis"